export const LOGIN = "LOGIN";
export const SIGNUP = "SIGNUP";

//Profile
export const CUSTOMER_PROFILE_UPDATE = "CUSTOMER_PROFILE_UPDATE";
export const CUSTOMER_PROFILE_GET = "CUSTOMER_PROFILE_GET";
export const RESTAURANT_PROFILE_UPDATE = "RESTAURANT_PROFILE_UPDATE";
export const RESTAURANT_PROFILE_GET = "RESTAURANT_PROFILE_GET";

//Dish
export const RESTAURANT_ADD_DISH = "RESTAURANT_ADD_DISH";
export const RESTAURANT_GET_ALL_DISH = "RESTAURANT_GET_ALL_DISH";
export const RESTAURANT_UPDATE_DISH =  "RESTAURANT_UPDATE_DISH";
export const CUSTOMER_GET_ALL_REST =  "CUSTOMER_GET_ALL_REST";


//Orders
export const GET_ORDERS_RESTAURANT = "GET_ORDERS_RESTAURANT";
export const CHANGE_ORDER_STATUS_RESTAURANT = "CHANGE_ORDER_STATUS_RESTAURANT";
export const MAKE_ORDER_CUSTOMER = "MAKE_ORDER_CUSTOMER";
export const GET_ALL_ORDERS_CUSTOMER = "GET_ALL_ORDERS_CUSTOMER";
export const CANCEL_ORDER_CUSTOMER = "CANCEL_ORDER_CUSTOMER";

//Events


//Reviews