export const LOGIN = "LOGIN";
export const SIGNUP = "SIGNUP";
export const CUSTOMER_PROFILE_UPDATE = "CUSTOMER_PROFILE_UPDATE";
export const CUSTOMER_PROFILE_GET = "CUSTOMER_PROFILE_GET";
export const RESTAURANT_PROFILE_UPDATE = "RESTAURANT_PROFILE_UPDATE";
export const RESTAURANT_PROFILE_GET = "RESTAURANT_PROFILE_GET";

